version: '1.0'
name: buildDocs
displayName: 构建文档
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
    commitMessages:
      include:
        - ^build.docs.*
stages:
  - name: build
    displayName: 构建
    strategy: fast
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - '# 下载pnpm'
          - npm i -g pnpm
          - '# 执行编译命令'
          - pnpm install && pnpm docs:build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./docs/.vitepress/libs
        caches:
          - ~/.npm
          - ~/.yarn
          - ~/.pnpm
        notify: []
        strategy:
          retry: '0'
